apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: frontend
        image: 619071328164.dkr.ecr.ap-south-1.amazonaws.com/front:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
