apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80       # Service port inside the cluster
      targetPort: 3000 # Port on the frontend pod
