name: Pre-Deployment Checks for Node.js App

on:
  push:
    branches:
      - master  # Runs when code is pushed to master
  pull_request:
    branches:
      - master  # Runs when a PR is opened to master

jobs:
  pre-checks:
    name: Run Pre-Deployment Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Require Manual Approval
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GIT_PT }}

  deploy:
    name: Deploy Node.js App
    needs: pre-checks  # Only runs if pre-checks pass
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying Node.js App..."
          # Example: Deploy to AWS, Azure, or any server
          # aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment
